graph TD
    ______________md["קרני הוד"]
    ___________md["נבואה"]
    __________md["סוכה"]
    __________________md["יום הכיפורים"]
    __________md["הכנה"]
    ________________md["נר שבת"]
    ______________________md["שיתוף מבואות"]
    ___________________md["מקח וממכר"]
    ____________________md["ערוב חצרות"]
    ____________________md["נשמה יתירה"]
    ___________________md["מצוות שבת"]
    __________________md["כבוד שבת"]
    _______________md["הוצאה"]
    ____________________md["בישול בשבת"]
    _______________md["קדושה אחת"]
    _________________md["סעודה חשובה"]
    ______________md["מתקן מנא"]
    _________________________md["קבורה ביו\"ט"]
    _______________________md["שמחת יו\"ט"]
    ____________________________________md["שיעור ע\"ת"]
    ___________________________________md["מקור ע\"ת"]
    ___________________________________md["מעשה ע\"ת"]
    ____________________________________________md["מין התבשילין לע\"ת"]
    _____________________________________________md["כמות התבשילין לע\"ת"]
    _______________________________________md["טעם תקנת ע\"ת"]
    __________________md["מתוך"]
    ___________________________md["מצוות יום טוב"]
    _________________________md["מלאכת עבודה"]
    ______________________________md["המבשל מיו\"ט לחול"]
    ___________________md["הואיל"]
    _______________md["הכנה דרבה"]
    ____________md["זכין"]
    _____________md["הגבהה"]
    _____________________md["קביעות בית דין"]
    _____________________md["קולייס האספנין"]
    _______________md["בית דירה"]
    ________________md["הילוך מיל"]
    __________________________md["שני כתובים המכחישים"]
    ___________md["שלוק"]
    _____________md["סמוכין"]
    ___________md["מתיר"]
    ____________________________md["מוסיף קדושה על קדושתו"]
    ___________md["כזית"]
    ____________md["דיבור"]
    _________________md["ביטול ברוב"]
    _____________________md["בנין בית המקדש"]
    ____________md["תנופה"]
    _________________________md["דומיא ללאו דחסימא"]
    ________________________md["לשון הגמרא והמקרא"]
    ____________md["סמיכה"]
    ___________________md["על מה גוזרין"]
    _______________________md["יעלה ויבא"]
    ____________________________md["תפילת ראש השנה"]
    ___________________md["תפילה"]
    _________________________________md["תפילת יו\"ט שחל בשבת"]
    ________________________md["ברכת המצוה"]
    _________________________md["קריאת התורה"]
    _____________________________md["פת הבאה בכיסנין"]
    ______________________________md["עיקר וטפל בברכות"]
    _________________________md["סעודה גדולה"]
    _________________________md["מים אחרונים"]
    ________________________md["ברכת המזון"]
    _____________________md["בשר בחלב"]
    _________________________________md["פת עכו\"ם"]
    _________________________________md["סתם יינם"]
    ____________________________________md["בישול עכו\"ם"]
    __________________________md["מאכלות אסורות"]
    ________________________md["כבוש כמבושל"]
    ______________________md["טעם כעיקר"]
    _______________md["דם"]
    _________________________md["אינו בן יומו"]
    ___________________md["תורה שבעל פה"]
    _________________md["הנותן מתנה"]
    _________________md --> ______________md
    _________________md --> ____________________md
    ________________________md --> _____________________md
    ________________________md --> ________________md
    ________________________md --> _______________md
    __________________________md --> ______________________md
    __________________________md --> _________________md
    __________________________md --> ____________________________________md
    ____________________________________md --> _________________________________md
    ____________________________________md --> _________________________________md
    ____________________________________md --> __________________________md
    ____________________________________md --> ______________________md
    ____________________________________md --> _________________md
    ____________________________________md --> _________________________md
    ____________________________________md --> ____________________md
    ____________________________________md --> ______________________________md
    _________________________________md --> ____________________________________md
    _________________________________md --> _________________________________md
    _________________________________md --> ____________________________________md
    _________________________________md --> ____________________________________md
    _________________________________md --> _____________________________md
    ________________________md --> _____________________________md
    _________________________md --> ___________md
    _____________________________md --> ________________________md
    _________________________md --> _____________md
    ____________________________md --> ___________________md
    ___________md --> _________________________md
    __________________________md --> _______________________md
    _____________md --> ______________________md
    _____________md --> ___________________________________md
    ________________________md --> _________________________md
    _______________md --> __________md
    _______________md --> _______________md
    _______________md --> ________________md
    _______________md --> ____________________md
    ____________md --> ____________________md
    _______________md --> __________md
    _______________md --> ___________________md
    ______________md --> ___________________md
    _______________md --> _________________________md
    ___________________md --> _________________________md
    ______________________________md --> ___________________md
    ______________________________md --> _______________md
    ______________________________md --> _________________________md
    _______________________md --> __________________________md
    _______________md --> ____________________md
    _______________md --> _______________md
    _______________md --> __________md
    _______________md --> __________________md
    ___________________md --> __________________md
    ___________________md --> ____________________________md
    ___________________md --> ________________md
    ____________________md --> _______________md
    ____________________md --> _______________md
    ____________________md --> ___________________________________md
    ____________________md --> __________md
    _______________________________________md --> ___________________md
    _______________________________________md --> ____________________________________________md
    _____________________________________________md --> _________________md
    ____________________________________________md --> ___________md
    ____________________________________________md --> _____________________md
    ____________________________________________md --> ________________________md
    ____________________________________________md --> ____________________________________md
    ____________________________________________md --> _________________________________md
    ____________________________________________md --> ____________________________________md
    ____________________________________________md --> ____________________________________md
    ____________________________________________md --> ___________md
    ____________________________________________md --> ____________________________________________md
    ___________________________________md --> ____________md
    ___________________________________md --> ____________md
    ___________________________________md --> ____________________md
    ___________________________________md --> _________________________md
    ____________________________________md --> ___________md
    ___________________md --> ______________md
    __________md --> _______________md
    __________md --> ______________md
    __________md --> _______________md
    __________md --> _________________________md
    __________md --> __________________md
    __________md --> __________________md
    __________________md --> _________________________md
    __________________md --> ________________md
    __________________md --> _______________md
    ______________________md --> _____________md
    __________md --> _______________md
    __________md --> _______________md
    ________________md --> ___________________________md
    ________________md --> _________________________md
    _________________________________md --> ___________________md
    _________________________________md --> _______________________md
    _________________________________md --> _______________________md
    ____________________________md --> ___________________md
    _______________________md --> _____________________md
    _______________________md --> ____________md
    ___________md --> _____________________md
    ______________md --> ___________________md
    _____________________md --> ___________md
    ________________________md --> ____________md
